package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemStockDo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.omg.CORBA.INTERNAL;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemStockDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon May 10 20:18:12 CST 2021
     */
    int deleteByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon May 10 20:18:12 CST 2021
     */
    int insert(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon May 10 20:18:12 CST 2021
     */
    int insertSelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon May 10 20:18:12 CST 2021
     */
    ItemStockDo selectByPrimaryKey(Integer id);


    ItemStockDo selectByItemId(Integer itemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon May 10 20:18:12 CST 2021
     */
    int updateByPrimaryKeySelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon May 10 20:18:12 CST 2021
     */
    int updateByPrimaryKey(ItemStockDo record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}